# Generated by Django 4.0 on 2024-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descriptions',
            field=models.TextField(default='text text text', max_length=500),
            preserve_default=False,
        ),
    ]
